### ISSUE TITLE
KeyError: 'response'报错

### ISSUE THREAD

**Issue by yinanzhaobaima** [o5-null/Lofter-Saver#1]
大佬好，试了好几个环境，换了好几个作者，还是报一样的错，求帮看下，报错KeyError: 'response'

测试例子：https://stangjiu.lofter.com/
在解析链接的时候报的错

![image](https://github.com/o5-null/Lofter-Saver/assets/42661974/8743b286-2013-44d9-bdc5-9be0600f3523)

Traceback (most recent call last):
  File "pywebio\session\threadbased.py", line 257, in run
  File "pywebio\output.py", line 805, in click_callback
  File "loftersaver_130_GUI.py", line 279, in start_url
  File "loftersaver_130_GUI.py", line 232, in lofter_list_print
  File "loftersaver_130_GUI.py", line 264, in lofter_down
  File "core.py", line 281, in lofter_api
KeyError: 'response'

**Comment by o5-null** [comment]
应该是lofter更改了接口导致的数据错误。我看看吧

**Comment by o5-null** [comment]
是文章被删除导致的报错。已解决。下载1.3bugfix版本即可

**Comment by o5-null** [comment]
竟然是吃严江粮的（笑

**Comment by o5-null** [comment]
有什么问题都可以加我Q。聊天也行（

**Comment by yinanzhaobaima** [comment]
感谢回复！果然可以下载了（嘿嘿严江真的很香
